# Generated by Django 4.1.6 on 2023-07-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('CE', 'Call'), ('PE', 'Put')], max_length=2)),
                ('strikePrice', models.IntegerField()),
                ('expiryDate', models.DateTimeField(auto_now_add=True)),
                ('IndexUnderlying', models.CharField(choices=[('NIFTY', 'NIFTY'), ('BANKNIFTY', 'BANKNIFTY'), ('FINNIFTY', 'FINNIFTY')], max_length=10)),
                ('lastPrice', models.SmallIntegerField()),
            ],
        ),
    ]
