# Generated by Django 4.1.6 on 2023-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='lotSize',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='option',
            name='expiryDate',
            field=models.DateTimeField(),
        ),
    ]
