# Generated by Django 4.1.6 on 2023-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0002_option_lotsize_alter_option_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='expiryDate',
            field=models.DateField(),
        ),
    ]
