# Generated by Django 4.1.6 on 2023-08-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
        ('Options', '0003_alter_option_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='stockUnderlying',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Stocks.stock'),
        ),
    ]
