# Generated by Django 4.1.6 on 2023-08-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stocks', '0001_initial'),
        ('Options', '0004_option_stockunderlying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='IndexUnderlying',
            field=models.CharField(blank=True, choices=[('NIFTY', 'NIFTY'), ('BANKNIFTY', 'BANKNIFTY'), ('FINNIFTY', 'FINNIFTY')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='stockUnderlying',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stocks.stock'),
        ),
    ]
