# Generated by Django 4.1.6 on 2023-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Options', '0005_alter_option_indexunderlying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='lastPrice',
            field=models.FloatField(default=0.0),
        ),
    ]
