# Generated by Django 4.1.6 on 2023-08-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
        ('Options', '0007_option_commodityunderlying'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='CryptoUnderlying',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crypto.crypto'),
        ),
    ]
