# Generated by Django 4.1.6 on 2023-08-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
        ('Commodity', '0001_initial'),
        ('Transcation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Commodity.commodity'),
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='cryto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crypto.crypto'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
